# Generated by Django 4.1.3 on 2022-11-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SickInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('footnum', models.ImageField(upload_to='')),
                ('date', models.DateTimeField()),
                ('drug', models.CharField(max_length=128)),
                ('vein', models.CharField(max_length=1)),
                ('needle', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'p_info',
            },
        ),
    ]
